# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: touch test.txt
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add test.txt
          git commit test.txt -m "Test"
      - run: gh pr create --draft --fill --base "main"
        env:
          GH_TOKEN: ${{ github.token }}
