# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - run: touch test.txt
      - run: gh pr create --draft --fill --base ${{ github.ref_name }} --head "new-branch"
        env:
          GH_TOKEN: ${{ github.token }}
