# This is a basic workflow to help you get started with Actions

name: TEST NAME

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - run: touch test.txt
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "test-branch"
          git add test.txt
          git commit test.txt -m "Test"
          git push -u origin "test-branch"
      - run: gh pr create --draft --fill --base ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ github.token }}
